/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ApiShelfRouteImport } from './routes/api/shelf'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageCatalogRouteImport } from './routes/manage.catalog'
import { Route as ManageCompanyRouteImport } from './routes/manage.company'
import { Route as ManageCustomersRouteImport } from './routes/manage.customers'
import { Route as ManageInventoryRouteImport } from './routes/manage.inventory'
import { Route as ManageOrdersRouteImport } from './routes/manage.orders'
import { Route as ManagePerformanceRouteImport } from './routes/manage.performance'
import { Route as ManagePromosRouteImport } from './routes/manage.promos'
import { Route as ManageRegisterRouteImport } from './routes/manage.register'
import { Route as ManageRunRouteImport } from './routes/manage.run'
import { Route as ManageScanRouteImport } from './routes/manage.scan'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShelfRoute = ApiShelfRouteImport.update({
  id: '/api/shelf',
  path: '/api/shelf',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCatalogRoute = ManageCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCompanyRoute = ManageCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCustomersRoute = ManageCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ManageRoute,
} as any)
const ManageInventoryRoute = ManageInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ManageRoute,
} as any)
const ManageOrdersRoute = ManageOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ManageRoute,
} as any)
const ManagePerformanceRoute = ManagePerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ManageRoute,
} as any)
const ManagePromosRoute = ManagePromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => ManageRoute,
} as any)
const ManageRegisterRoute = ManageRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ManageRoute,
} as any)
const ManageRunRoute = ManageRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => ManageRoute,
} as any)
const ManageScanRoute = ManageScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => ManageRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/manage': typeof ManageRouteWithChildren
  '/orders': typeof OrdersRoute
  '/api/shelf': typeof ApiShelfRoute
  '/manage/catalog': typeof ManageCatalogRoute
  '/manage/company': typeof ManageCompanyRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/inventory': typeof ManageInventoryRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/performance': typeof ManagePerformanceRoute
  '/manage/promos': typeof ManagePromosRoute
  '/manage/register': typeof ManageRegisterRoute
  '/manage/run': typeof ManageRunRoute
  '/manage/scan': typeof ManageScanRoute
  '/product/$id': typeof ProductIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/api/shelf': typeof ApiShelfRoute
  '/manage/catalog': typeof ManageCatalogRoute
  '/manage/company': typeof ManageCompanyRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/inventory': typeof ManageInventoryRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/performance': typeof ManagePerformanceRoute
  '/manage/promos': typeof ManagePromosRoute
  '/manage/register': typeof ManageRegisterRoute
  '/manage/run': typeof ManageRunRoute
  '/manage/scan': typeof ManageScanRoute
  '/product/$id': typeof ProductIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/manage': typeof ManageRouteWithChildren
  '/orders': typeof OrdersRoute
  '/api/shelf': typeof ApiShelfRoute
  '/manage/catalog': typeof ManageCatalogRoute
  '/manage/company': typeof ManageCompanyRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/inventory': typeof ManageInventoryRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/performance': typeof ManagePerformanceRoute
  '/manage/promos': typeof ManagePromosRoute
  '/manage/register': typeof ManageRegisterRoute
  '/manage/run': typeof ManageRunRoute
  '/manage/scan': typeof ManageScanRoute
  '/product/$id': typeof ProductIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/manage'
    | '/orders'
    | '/api/shelf'
    | '/manage/catalog'
    | '/manage/company'
    | '/manage/customers'
    | '/manage/inventory'
    | '/manage/orders'
    | '/manage/performance'
    | '/manage/promos'
    | '/manage/register'
    | '/manage/run'
    | '/manage/scan'
    | '/product/$id'
    | '/receipt/$id'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/orders'
    | '/api/shelf'
    | '/manage/catalog'
    | '/manage/company'
    | '/manage/customers'
    | '/manage/inventory'
    | '/manage/orders'
    | '/manage/performance'
    | '/manage/promos'
    | '/manage/register'
    | '/manage/run'
    | '/manage/scan'
    | '/product/$id'
    | '/receipt/$id'
    | '/manage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/manage'
    | '/orders'
    | '/api/shelf'
    | '/manage/catalog'
    | '/manage/company'
    | '/manage/customers'
    | '/manage/inventory'
    | '/manage/orders'
    | '/manage/performance'
    | '/manage/promos'
    | '/manage/register'
    | '/manage/run'
    | '/manage/scan'
    | '/product/$id'
    | '/receipt/$id'
    | '/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ManageRoute: typeof ManageRouteWithChildren
  OrdersRoute: typeof OrdersRoute
  ApiShelfRoute: typeof ApiShelfRoute
  ProductIdRoute: typeof ProductIdRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shelf': {
      id: '/api/shelf'
      path: '/api/shelf'
      fullPath: '/api/shelf'
      preLoaderRoute: typeof ApiShelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/catalog': {
      id: '/manage/catalog'
      path: '/catalog'
      fullPath: '/manage/catalog'
      preLoaderRoute: typeof ManageCatalogRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/company': {
      id: '/manage/company'
      path: '/company'
      fullPath: '/manage/company'
      preLoaderRoute: typeof ManageCompanyRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/customers': {
      id: '/manage/customers'
      path: '/customers'
      fullPath: '/manage/customers'
      preLoaderRoute: typeof ManageCustomersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/inventory': {
      id: '/manage/inventory'
      path: '/inventory'
      fullPath: '/manage/inventory'
      preLoaderRoute: typeof ManageInventoryRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/orders': {
      id: '/manage/orders'
      path: '/orders'
      fullPath: '/manage/orders'
      preLoaderRoute: typeof ManageOrdersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/performance': {
      id: '/manage/performance'
      path: '/performance'
      fullPath: '/manage/performance'
      preLoaderRoute: typeof ManagePerformanceRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/promos': {
      id: '/manage/promos'
      path: '/promos'
      fullPath: '/manage/promos'
      preLoaderRoute: typeof ManagePromosRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/register': {
      id: '/manage/register'
      path: '/register'
      fullPath: '/manage/register'
      preLoaderRoute: typeof ManageRegisterRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/run': {
      id: '/manage/run'
      path: '/run'
      fullPath: '/manage/run'
      preLoaderRoute: typeof ManageRunRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/scan': {
      id: '/manage/scan'
      path: '/scan'
      fullPath: '/manage/scan'
      preLoaderRoute: typeof ManageScanRouteImport
      parentRoute: typeof ManageRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManageRouteChildren {
  ManageCatalogRoute: typeof ManageCatalogRoute
  ManageCompanyRoute: typeof ManageCompanyRoute
  ManageCustomersRoute: typeof ManageCustomersRoute
  ManageInventoryRoute: typeof ManageInventoryRoute
  ManageOrdersRoute: typeof ManageOrdersRoute
  ManagePerformanceRoute: typeof ManagePerformanceRoute
  ManagePromosRoute: typeof ManagePromosRoute
  ManageRegisterRoute: typeof ManageRegisterRoute
  ManageRunRoute: typeof ManageRunRoute
  ManageScanRoute: typeof ManageScanRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageCatalogRoute: ManageCatalogRoute,
  ManageCompanyRoute: ManageCompanyRoute,
  ManageCustomersRoute: ManageCustomersRoute,
  ManageInventoryRoute: ManageInventoryRoute,
  ManageOrdersRoute: ManageOrdersRoute,
  ManagePerformanceRoute: ManagePerformanceRoute,
  ManagePromosRoute: ManagePromosRoute,
  ManageRegisterRoute: ManageRegisterRoute,
  ManageRunRoute: ManageRunRoute,
  ManageScanRoute: ManageScanRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ManageRoute: ManageRouteWithChildren,
  OrdersRoute: OrdersRoute,
  ApiShelfRoute: ApiShelfRoute,
  ProductIdRoute: ProductIdRoute,
  ReceiptIdRoute: ReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
